runtime: go
api_version: go1

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: _go_app
    secure: always
  - url: /api/deleteexpirehashrate
    script: _go_app
    login: admin